const $=id=>document.getElementById(id);
async function api(url,opt={}){const r=await fetch(url,opt);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Erro");return d;}
async function boot(){const me=await api("/api/me");if(me.admin)showDash();}
function showDash(){$("loginBox").classList.add("hidden");$("dash").classList.remove("hidden");loadAdmin();loadEvents();}
$("loginForm").addEventListener("submit",async e=>{e.preventDefault();$("loginMsg").textContent="";try{await api("/api/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:$("password").value})});showDash()}catch(err){$("loginMsg").textContent=err.message}});
$("logout").onclick=async()=>{await api("/api/logout",{method:"POST"});location.reload()};

async function loadAdmin(){const songs=await api("/api/songs");const el=$("adminSongs");el.innerHTML=songs.length?songs.map(s=>`<div class="admin-item"><img class="admin-cover" src="${s.coverUrl||""}" onerror="this.style.display='none'"><div class="admin-info"><strong>${esc(s.title)}</strong><div class="meta">${esc(s.genre||"")} ${s.year?"• "+esc(s.year):""}</div></div><div class="admin-actions"><button class="btn small" onclick='editSong(${JSON.stringify(s)})'>EDITAR</button><button class="btn ghost small" onclick="delSong('${s.id}')">APAGAR</button></div></div>`).join(""):'<p class="loading">Ainda não tens músicas.</p>'}
function editSong(s){$("songId").value=s.id;$("title").value=s.title||"";$("artist").value=s.artist||"DJ BlackBurn";$("genre").value=s.genre||"";$("year").value=s.year||"";$("description").value=s.description||"";$("audio").required=false;$("formTitle").textContent="Editar música";$("saveBtn").textContent="GUARDAR ALTERAÇÕES";$("cancelEdit").classList.remove("hidden");window.scrollTo({top:0,behavior:"smooth"})}
$("cancelEdit").onclick=resetForm;
function resetForm(){$("songForm").reset();$("artist").value="DJ BlackBurn";$("songId").value="";$("audio").required=true;$("formTitle").textContent="Adicionar música";$("saveBtn").textContent="GUARDAR MÚSICA";$("cancelEdit").classList.add("hidden");$("formMsg").textContent=""}
$("songForm").addEventListener("submit",async e=>{e.preventDefault();$("formMsg").textContent="A enviar...";const id=$("songId").value;const fd=new FormData(e.target);try{await api(id?"/api/songs/"+id:"/api/songs",{method:id?"PUT":"POST",body:fd});$("formMsg").textContent="Guardado com sucesso.";resetForm();await loadAdmin()}catch(err){$("formMsg").textContent=err.message}});
async function delSong(id){if(!confirm("Apagar esta música?"))return;try{await api("/api/songs/"+id,{method:"DELETE"});loadAdmin()}catch(e){alert(e.message)}}

async function loadEvents(){const events=await api("/api/events");const el=$("adminEvents");el.innerHTML=events.length?events.map(e=>`<div class="admin-item"><img class="admin-cover" src="${e.posterUrl||""}" onerror="this.style.display='none'"><div class="admin-info"><strong>${esc(e.title)}</strong><div class="meta">${formatDate(e.event_date)}${e.event_time?" • "+esc(e.event_time):""}${e.city?" • "+esc(e.city):""}</div><div class="meta">${esc(e.venue||"")}</div></div><div class="admin-actions"><button class="btn small" onclick='editEvent(${JSON.stringify(e)})'>EDITAR</button><button class="btn ghost small" onclick="delEvent('${e.id}')">APAGAR</button></div></div>`).join(""):'<p class="loading">Ainda não tens eventos.</p>'}
function formatDate(v){if(!v)return "";const p=String(v).split("-");return p.length===3?p[2]+"/"+p[1]+"/"+p[0]:String(v)}
function editEvent(e){$("eventId").value=e.id;$("eventTitle").value=e.title||"";$("eventVenue").value=e.venue||"";$("eventCity").value=e.city||"";$("eventDate").value=(e.event_date||"").slice(0,10);$("eventTime").value=(e.event_time||"").slice(0,5);$("eventDescription").value=e.description||"";$("eventFormTitle").textContent="Editar evento";$("eventSaveBtn").textContent="GUARDAR ALTERAÇÕES";$("cancelEventEdit").classList.remove("hidden");window.scrollTo({top:0,behavior:"smooth"})}
function resetEventForm(){$("eventForm").reset();$("eventId").value="";$("eventFormTitle").textContent="Adicionar evento";$("eventSaveBtn").textContent="GUARDAR EVENTO";$("cancelEventEdit").classList.add("hidden");$("eventMsg").textContent=""}
$("cancelEventEdit").onclick=resetEventForm;
$("eventForm").addEventListener("submit",async e=>{e.preventDefault();$("eventMsg").textContent="A enviar...";const id=$("eventId").value;const fd=new FormData(e.target);try{await api(id?"/api/events/"+id:"/api/events",{method:id?"PUT":"POST",body:fd});$("eventMsg").textContent="Evento guardado.";resetEventForm();await loadEvents()}catch(err){$("eventMsg").textContent=err.message}});
async function delEvent(id){if(!confirm("Apagar este evento?"))return;try{await api("/api/events/"+id,{method:"DELETE"});loadEvents()}catch(e){alert(e.message)}}
function esc(x){return String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));}
boot();
