const $=id=>document.getElementById(id);
async function api(url,opt={}){const r=await fetch(url,opt);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Erro");return d;}
async function boot(){const me=await api("/api/me"); if(me.admin) showDash();}
function showDash(){$("loginBox").classList.add("hidden");$("dash").classList.remove("hidden");loadAdmin();}
$("loginForm").addEventListener("submit",async e=>{e.preventDefault();$("loginMsg").textContent="";try{await api("/api/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:$("password").value})});showDash()}catch(err){$("loginMsg").textContent=err.message}});
$("logout").onclick=async()=>{await api("/api/logout",{method:"POST"});location.reload()};
async function loadAdmin(){const songs=await api("/api/songs");const el=$("adminSongs");el.innerHTML=songs.length?songs.map(s=>`<div class="admin-item"><img class="admin-cover" src="${s.coverUrl||""}" onerror="this.style.display='none'"><div class="admin-info"><strong>${esc(s.title)}</strong><div class="meta">${esc(s.genre||"")} ${s.year?"• "+esc(s.year):""}</div></div><div class="admin-actions"><button class="btn small" onclick='editSong(${JSON.stringify(s)})'>EDITAR</button><button class="btn ghost small" onclick="delSong('${s.id}')">APAGAR</button></div></div>`).join(""):'<p class="loading">Ainda não tens músicas.</p>'}
function editSong(s){$("songId").value=s.id;$("title").value=s.title||"";$("artist").value=s.artist||"DJ BlackBurn";$("genre").value=s.genre||"";$("year").value=s.year||"";$("description").value=s.description||"";$("audio").required=false;$("formTitle").textContent="Editar música";$("saveBtn").textContent="GUARDAR ALTERAÇÕES";$("cancelEdit").classList.remove("hidden");window.scrollTo({top:0,behavior:"smooth"})}
$("cancelEdit").onclick=resetForm;
function resetForm(){$("songForm").reset();$("artist").value="DJ BlackBurn";$("songId").value="";$("audio").required=true;$("formTitle").textContent="Adicionar música";$("saveBtn").textContent="GUARDAR MÚSICA";$("cancelEdit").classList.add("hidden");$("formMsg").textContent=""}
$("songForm").addEventListener("submit",async e=>{e.preventDefault();$("formMsg").textContent="A enviar...";const id=$("songId").value;const fd=new FormData(e.target);try{await api(id?"/api/songs/"+id:"/api/songs",{method:id?"PUT":"POST",body:fd});$("formMsg").textContent="Guardado com sucesso.";resetForm();await loadAdmin()}catch(err){$("formMsg").textContent=err.message}});
async function delSong(id){if(!confirm("Apagar esta música?"))return;try{await api("/api/songs/"+id,{method:"DELETE"});loadAdmin()}catch(e){alert(e.message)}}
function esc(x){return String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));}
boot();